name: Behat

on:
  pull_request:
    branches: behat-carl
  push:
    branches: behat-carl

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: moodle
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: phar, iconv, mbstring, gd, intl, sodium, zip
          tools: composer

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y firefox wget openjdk-11-jre

      - name: Set up MariaDB Data Directory and Permissions
        run: |
          sudo chmod 777 /etc/mysql

      - name: Set up geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialise Moodle (creates config.php)
        run: |
          export LANG="en_AU.UTF-8"
          export LC_ALL="en_AU.UTF-8"
          export PHPRC=`realpath /etc/php/8.3/cli/php.ini`
          
          REPO_ROOT="`pwd`"
          cd "$REPO_ROOT"/server/moodle
          php admin/cli/install.php \
              --lang=en \
              --wwwroot="http://127.0.0.1:8000/" \
              --dataroot="$REPO_ROOT/server/moodledata" \
              --dbtype=mysqli \
              --dbhost=127.0.0.1 \
              --dbname=moodle \
              --dbuser=root \
              --dbpass=root \
              --dbport=3306 \
              --non-interactive \
              --agree-license \
              --fullname="Moodle Testing" \
              --shortname="MT" \
              --adminpass="hunter2"
              
      - name: Start PHP Server
        run: |
          php -S 127.0.0.1:8000 -t server/moodle &

      - name: Set up Selenium
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.25.0/selenium-server-4.25.0.jar
          java -jar selenium-server-4.25.0.jar standalone &

      - name: Install & Init Behat
        run: | 
          cd server/moodle
          echo '$CFG->behat_dataroot = "$CFG->dataroot/behat";' >> config.php
          echo '$CFG->behat_prefix = "beh_";' >> config.php
          echo '$CFG->behat_wwwroot = "http://127.0.0.1:8000";' >> config.php

          # Install dependencies and initialize Behat
          composer install
          php admin/tool/behat/cli/init.php

      - name: Run Behat Tests
        run: |
          cd server/moodle
          vendor/bin/behat --config "$CFG->behat_dataroot/behat/behat.yml" -vv
